# Generated by Django 4.1.2 on 2023-03-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='give full abbrevation of your test', max_length=20, unique=True)),
                ('start_time', models.DateTimeField(verbose_name='Test Starting time')),
                ('end_time', models.DateTimeField(verbose_name='Test Ending time')),
                ('questions', models.ManyToManyField(to='core.question')),
            ],
        ),
    ]
