# Generated by Django 4.1.7 on 2023-03-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_question_negative_score_question_positive_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name="testresult",
            table="TestResult",
        ),
    ]
