# Generated by Django 4.1.7 on 2023-03-11 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_answer_score_alter_testresult_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testresult",
            name="id",
        ),
        migrations.AlterModelTable(
            name="testresult",
            table=None,
        ),
    ]
